apiVersion: apps/v1
kind: Deployment
metadata:
  name: mloe-flask-workshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mloe-flask-workshop
  template:
    metadata:
      labels:
        app: mloe-flask-workshop
    spec:
      containers:
      - name: mloe-flask-workshop
        image: ballchuuuu/mloe_flask_workshop_xx1
        resources:
          limits:
            nvidia.com/gpu: 1
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: mloe-flask-workshop
spec:
  type: LoadBalancer
  ports:
  - port: 5000
  selector:
    app: mloe-flask-workshop